import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainWithAside from "@/components/page/main-with-aside";
import Navbar from "@/components/page/navbar";
import { ReactQueryProvider } from "@/providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reddit - The heart of the internet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0e1113] text-neutral-100 min-h-screen flex flex-col`}
      >
        <ReactQueryProvider>
          <Navbar />
          <MainWithAside>{children}</MainWithAside>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
